version: 1

disable_existing_loggers: false

formatters:
  default:
    format: "[%(levelname)s] %(asctime)s %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: python-runner.log
    when: midnight
    interval: 1
    backupCount: 14
    encoding: utf-8
    delay: true

root:
  level: INFO
  handlers: [console, file]

loggers:
  runner:
    level: INFO
    propagate: false
    handlers: [console, file]

  executor:
    level: INFO
    propagate: false
    handlers: [console, file]

  handler:
    level: INFO
    propagate: false
    handlers: [console, file]
